# Generated by Django 5.0.2 on 2024-02-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
    ]
